---
title: "Application of Response Surface Method on Non-linear System Optimization: Paper Drone Experiment"
author: "Donghyun Ko"
date: last-modified
categories: ["Optimization", "Response Surface Method"]
format:
  html: default
---

The goal of this research is to find the most influential factors for the flying time of a paper drone by using a variety of methodologies from design and analysis of the industrial engineering, and to suggest the final optimized design of a paper drone so that it can fly as long as possible. By applying a variety of design methods, we can build an optimized model to make the best product or system, and this helps us reduce the cost of changing the process conditions so that we can minimize the number of experiment runs to reduce the total cost. We designed the experiment with standard papers given by NASA spaceship center. We set a total 6 factors and investigate the response surface of a paper drone flight time. With this research, we showed that RSM is not an independent way of designing an experiment in isolation, but the perfect way of combinations for those to find the optimal design, and the RSM process will help us to understand the practical way of design any experiment.


**Full paper:** [Download PDF](../files/research_2.pdf)